# -*- mode: ruby -*-
# vi: set ft=ruby :


$infoScript = <<SCRIPT
  echo 'Keycloak-Server'
  echo 'Admin console: http://localhost:8888/auth/'
  echo 'Keycloak admin user: keycloak_admin'
  echo 'Keycloak password: k6ycloakAdmin'
  echo 'IP addresses of the VM' 
  # da das Netzwerk auf privat gestellt ist -> tail
  ifconfig | grep 'inet A' | grep Bcast | awk '{print $2}' | sed 's/addr://' | tail -n 1
SCRIPT
Vagrant.configure(2) do |config|
#  config.vm.box = "bento/ubuntu-16.04"
  config.vm.box = "ubuntu/trusty64"
  config.vm.box_check_update = false
  config.vm.hostname = "keycloak"
  #config.vm.network "private_network", type: "dhcp"
  config.vm.network "forwarded_port", guest: 8080, host: 8888
  config.vm.provider "virtualbox" do |vb|
     vb.name = "keycloak"
     vb.customize ["modifyvm", :id, "--cpuexecutioncap", "50"]
     vb.memory = "1024"
     vb.cpus = 2
  end
  config.vm.provision "shell", path: "scripts/bootstrap.sh"
  config.vm.provision "shell", path: "scripts/download_keycloak.sh"
# call manually ... needs java8
  config.vm.provision "shell", path: "scripts/install_java.sh"
  config.vm.provision "shell", path: "scripts/install_tomcat8.sh"
#  config.vm.provision "shell", path: "scripts/install_tomcat9.sh"
  config.vm.provision "shell", path: "scripts/install_keycloak.sh"
  config.vm.provision "shell", inline: $infoScript,
      run: "always"
end
